language: java

notifications:
  email:
    recepients:
      - omid-ci@yahoo-inc.com
  on_success: always
  on_failure: always

jdk:
  - oraclejdk8

branches:
  only:
    - open-source

before_script:
  # This is required to avoid failures of HBase minicluster related to Hadoop 1.x releases
  - umask 022
  - git config --global user.email "omid-ci@yahoo-inc.com"
  - git config --global user.name "Omid CI"
  - git checkout open-source

script:
  - echo "NOOP"

after_success:
  - travis_wait mvn cobertura:cobertura coveralls:report
  - mvn -B release:prepare release:perform -Pdeploy_profile --settings bintray-settings.xml

after_failure:
  - cat common/target/surefire-reports/*.txt
  - cat statemachine/target/surefire-reports/*.txt
  - cat metrics/target/surefire-reports/*.txt
  - cat codahale-metrics/target/surefire-reports/*.txt
  - cat hbase-client/target/surefire-reports/*.txt
  - cat transaction-client/target/surefire-reports/*.txt
  - cat tso-server/target/surefire-reports/*.txt
  - cat commit-table/target/surefire-reports/*.txt
  - cat hbase-commit-table/target/surefire-reports/*.txt
  - cat hbase-coprocessor/target/surefire-reports/*.txt
  - cat benchmarks/target/surefire-reports/*.txt
