# Secure HBase credentials, core-site.xml and hbase-site.xml are expected to be in the classpath
# It's used for secure HBase only and ignored otherwise
# principal: omid_hbase_client
# keytab: /path/to/hbase/client/keytab

omidClientConfiguration: !!com.yahoo.omid.tsoclient.OmidClientConfiguration
    connectionString: "localhost:54758"

metrics: !!com.yahoo.omid.metrics.CodahaleMetricsProvider [
    !!com.yahoo.omid.metrics.CodahaleMetricsConfig {
        outputFreqTimeUnit: !!java.util.concurrent.TimeUnit SECONDS,
        outputFreq: 1,
        reporters: !!set {
            !!com.yahoo.omid.metrics.CodahaleMetricsConfig$Reporter CSV,
            !!com.yahoo.omid.metrics.CodahaleMetricsConfig$Reporter CONSOLE
            },
        csvDir: "csvMetrics",
        prefix: "somePrefix",
      }
]

