# =====================================================================================================================
#
# Omid TSO Server Configuration
# ---------------------------------------------------------------------------------------------------------------------
#
# Tune here the default values for TSO server config parameters found in 'default-omid-server-configuration.yml' file
#
# =====================================================================================================================
