#HBase related
commitTableName: OMID_COMMIT_TABLE

#TSO/HA connection
omidClientConfiguration: !!com.yahoo.omid.tso.client.OmidClientConfiguration [ ]

#Instrumentation
metrics: !!com.yahoo.omid.metrics.NullMetricsProvider [ ]