#HBase related
commitTableName: OMID_COMMIT_TABLE

#TSO/HA connection
omidClientConfiguration: !!org.apache.omid.tso.client.OmidClientConfiguration [ ]

#Instrumentation
metrics: !!org.apache.omid.metrics.NullMetricsProvider [ ]